version: "3.5"

services:

  cache-redis:
    image: redis
    container_name: redis-django-elearning
    ports:
      - "6380:6379" # host:guest
    volumes:
      - ./data/cache/:/data

#      https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/
  webservice:
    build:
      context: .
    restart: unless-stopped
    container_name: webservice-django-elearning
    volumes:
      - ./:/code/  # shares media files and unix socket with the host
    depends_on:
      - db
      - cache-redis
    env_file:
      - .env.prod
    entrypoint: /code/entrypoint.sh
    command: ["./wait-for-it.sh", "db:5432", "--" , "uwsgi" , "--ini", "/code/config/uwsgi/uwsgi.ini",]

# ASGI server for channels app
#  https://github.com/django/daphne
  daphne:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/code/ # shares unix socket with the host
    env_file:
      - .env.prod
    depends_on:
      - db
      - cache-redis
#    --u defines the location of the socket
    command: ["./wait-for-it.sh", "db:5432", "--" , "daphne" , "-u", "/code/config/daphne.sock", "config.asgi:application"]


  db:
    image: postgres
    restart: unless-stopped
    container_name: db-django-elearning
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5433:5432"


  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx-django-elearning
    volumes:
      - ./nginx/:/etc/nginx/templates/
      - ./:/code # to access static files and the socket
    ports:
      - "80:80"

